# If someone with write access comments "/ok-to-test" on a pull request, emit a repository_dispatch event
name: Label
on:
  issue_comment:
    types: [created]
jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
    - name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v1
      if: github.base_ref == 'master'
      with:
        token: ${{ secrets.CI_REGISTRY_TOKEN }} # PAT or OAuth token will also work
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        issue-type: pull-request
        commands: ok-to-test
        named-args: true
        permission: write
    - name: Slash Command Dispatch for release 2020.06
      uses: peter-evans/slash-command-dispatch@v1
      if: github.base_ref == 'release-2020.06'
      with:
        token: ${{ secrets.CI_REGISTRY_TOKEN }} # PAT or OAuth token will also work
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        issue-type: pull-request
        commands: ok-to-test
        named-args: true
        event-type-suffix: -release-2020.06
        permission: write
    - name: Dump the client payload context
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      run: echo "$PAYLOAD_CONTEXT"
